#!/usr/bin/env bash
# install-sublime.sh — set up Sublime Text from these dotfiles. Linux and macOS.
#
#   ./install-sublime.sh              link the User/ config
#   ./install-sublime.sh --dry-run    show what would happen, change nothing
#   ./install-sublime.sh --force      replace differing files without asking
#   ./install-sublime.sh --prune      also remove installed packages that are
#                                     neither in Package Control.sublime-settings
#                                     nor in sublime/prune-keep.txt
#   ./install-sublime.sh --uninstall  remove the links, restore the backups
#
# Config files are symlinked, so editing them in Sublime edits this repo. Any
# real file in the way is backed up as <name>.bak-<timestamp> first, and a file
# that differs from the repo's is never replaced without asking.
#
# Packages themselves are installed by Package Control on next launch, from the
# installed_packages list in User/Package Control.sublime-settings. Packages you
# installed by hand cannot go in that list — Package Control cannot install them
# and deletes them as orphans — so name them in sublime/prune-keep.txt and
# --prune leaves them alone.
#
# --prune refuses to run unless User/Package Control.sublime-settings is linked
# to the repo's copy. Otherwise Sublime and this script read different lists and
# each undoes the other: prune removes a package, Package Control downloads it
# again, and every run drops another .removed-* directory.

set -euo pipefail

DOTFILES=$(cd "$(dirname "$0")" && pwd)
SRC="$DOTFILES/sublime/User"
KEEP="$DOTFILES/sublime/prune-keep.txt"
STAMP=$(date +%Y%m%d-%H%M%S)
DRY=0; FORCE=0; PRUNE=0; UNINSTALL=0

while [ $# -gt 0 ]; do
  case $1 in
    --dry-run)   DRY=1 ;;
    --force)     FORCE=1 ;;
    --prune)     PRUNE=1 ;;
    --uninstall) UNINSTALL=1 ;;
    -h|--help)   sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
  shift
done

case "$(uname -s)" in
  Darwin) SUBL_DIR="$HOME/Library/Application Support/Sublime Text" ;;
  Linux)  SUBL_DIR="$HOME/.config/sublime-text"
          [ -d "$SUBL_DIR" ] || [ ! -d "$HOME/.config/sublime-text-3" ] || SUBL_DIR="$HOME/.config/sublime-text-3" ;;
  *) echo "unsupported OS: $(uname -s)" >&2; exit 1 ;;
esac
DST="$SUBL_DIR/Packages/User"

say() { printf '  %s\n' "$*"; }
run() { if [ "$DRY" -eq 1 ]; then printf '  [dry-run] %s\n' "$*"; else "$@"; fi; }

# Generated by packages, not config — never link these.
skip() {
  case $1 in
    .DS_Store|.git|*.bak.*|*.bak-*) return 0 ;;
    "Package Control.user-ca-bundle") return 0 ;;
    __pycache__|*.pyc) return 0 ;;      # bytecode plugina, ne konfiguracija
    GitSavvy|Terminus) return 0 ;;      # directories of generated colour schemes
    *) return 1 ;;
  esac
}

link() {
  local src=$1 dst=$2
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then say "ok    ${dst#$DST/}"; return; fi
  if [ -e "$dst" ] && [ ! -L "$dst" ] && ! cmp -s "$dst" "$src"; then
    local n; n=$(diff "$dst" "$src" 2>/dev/null | grep -c '^[<>]' || true)
    say "DIFFERS  ${dst#$DST/}  ($n lines vs the repo's copy)"
    if [ "$FORCE" -eq 1 ]; then say "         --force: replacing (backed up)"
    elif [ "$DRY" -eq 1 ]; then say "         would ask before replacing"
    elif [ -t 0 ]; then
      printf '         replace it? it is backed up either way [y/N] '
      local a; read -r a; case $a in [yY]*) ;; *) say "         kept"; return ;; esac
    else
      say "         SKIPPED (not a terminal). Compare, then --force, or copy yours in:"
      say "           cp \"$dst\" \"$src\""
      return
    fi
  fi
  run mkdir -p "$(dirname "$dst")"
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    run mv "$dst" "$dst.bak-$STAMP"; say "moved ${dst#$DST/} -> $(basename "$dst").bak-$STAMP"
  fi
  run ln -s "$src" "$dst"
  say "link  ${dst#$DST/}"
}

# ---------------------------------------------------------------- uninstall
if [ "$UNINSTALL" -eq 1 ]; then
  echo; echo "  removing Sublime config links"; echo
  find "$SRC" -type f | while read -r src; do
    rel=${src#$SRC/}; dst="$DST/$rel"
    [ -L "$dst" ] || continue
    run rm "$dst"
    newest=$(ls -1dt "$dst".bak-* 2>/dev/null | head -1 || true)
    if [ -n "$newest" ]; then run mv "$newest" "$dst"; say "restored $rel"
    else say "removed  $rel"; fi
  done
  echo; say "done"; echo; exit 0
fi

echo
echo "  sublime dotfiles -> $DST   ($(uname -s))"
[ "$DRY" -eq 1 ] && echo "  DRY RUN — nothing will change"
echo

if [ ! -d "$DST" ]; then
  echo "  Sublime's User folder does not exist: $DST" >&2
  echo "  Install Sublime Text and launch it once, then re-run." >&2
  exit 1
fi

# ---------------------------------------------------------------- link config
# find, so nested files (mytheme/) are linked individually rather than the
# directory being replaced wholesale
find "$SRC" -type f | sort | while read -r src; do
  rel=${src#$SRC/}
  base=${rel%%/*}
  skip "$base" && continue
  skip "$(basename "$rel")" && continue
  link "$src" "$DST/$rel"
done

# --------------------------------------------------- drop links we orphaned
# A file removed from the repo leaves a dangling symlink behind, which Sublime
# then reports as a missing resource. Only links pointing into this repo are
# touched; anything else in User/ is not ours to remove.
find "$DST" -type l 2>/dev/null | while read -r l; do
  t=$(readlink "$l") || continue
  case $t in "$SRC"/*) ;; *) continue ;; esac
  [ -e "$t" ] && continue
  run rm "$l"
  say "unlink ${l#$DST/}  (gone from the repo)"
done
# and the empty directories those links may leave
find "$DST" -type d -empty -not -path "$DST" 2>/dev/null | while read -r d; do
  run rmdir "$d" 2>/dev/null && say "rmdir  ${d#$DST/}"
done

# ---------------------------------------------------------------- prune
if [ "$PRUNE" -eq 1 ]; then
  echo
  IP="$SUBL_DIR/Installed Packages"
  PC_SRC="$SRC/Package Control.sublime-settings"
  PC_DST="$DST/Package Control.sublime-settings"

  # Sublime reads the User/ copy of this file; --prune reads the repo's. When
  # they are not the same file the two disagree: prune moves a package away,
  # Package Control sees it missing from ITS list and downloads it again, and
  # the next run leaves another .removed-* directory behind. Refuse instead of
  # looping. Linking it (answer y above, or --force) makes both read one list.
  if [ ! -L "$PC_DST" ] || [ "$(readlink "$PC_DST")" != "$PC_SRC" ]; then
    if [ "$DRY" -eq 1 ] && [ "$FORCE" -eq 1 ]; then
      # --force would have linked it above, so preview the prune as if it had.
      say "note  $(basename "$PC_DST") would be linked first, so prune can run"
    else
      say "NOT PRUNING  $PC_DST is not linked to the repo's copy."
      say "             Package Control would reinstall whatever prune removes."
      say "             Link it first, then prune:"
      say "               ./install-sublime.sh --force --prune"
      if [ "$DRY" -eq 1 ]; then PRUNE=0; else exit 1; fi
    fi
  fi
fi

if [ "$PRUNE" -eq 1 ]; then
  want=$(sed -n 's/^[[:space:]]*"\(.*\)",\{0,1\}$/\1/p' "$PC_SRC" \
         | sed -n '/^[A-Za-z]/p')
  # Packages installed by hand cannot go in installed_packages — Package Control
  # does not know them, would fail to install them, and would delete them as
  # orphans. They are named in prune-keep.txt instead, and prune skips them.
  kept=0
  pruned=0
  if [ -f "$KEEP" ]; then
    keep=$(sed -e 's/#.*//' -e 's/[[:space:]]*$//' "$KEEP" | sed -n '/./p')
    if [ -n "$keep" ]; then
      kept=$(printf '%s\n' "$keep" | wc -l | tr -d ' ')
      want=$(printf '%s\n%s\n' "$want" "$keep")
      say "protecting $kept hand-installed package(s) from $(basename "$KEEP"):"
      printf '%s\n' "$keep" | while read -r k; do say "  $k"; done
    fi
  else
    say "note  no $KEEP — hand-installed packages are NOT protected"
  fi
  if [ -d "$IP" ]; then
    for p in "$IP"/*.sublime-package; do
      [ -e "$p" ] || continue
      name=$(basename "$p" .sublime-package)
      [ "$name" = "Package Control" ] && continue
      if printf '%s\n' "$want" | grep -qxF "$name"; then continue; fi
      run mkdir -p "$IP/.removed-$STAMP"
      run mv "$p" "$IP/.removed-$STAMP/"
      say "pruned $name"
      pruned=$((pruned + 1))
    done
  fi
  # Unpacked packages live in Packages/ instead, and prune has to look there too
  # or something like Terminal (unpacked) survives a prune that removes its
  # packed equivalents.
  for d in "$SUBL_DIR"/Packages/*/; do
    [ -d "$d" ] || continue
    name=$(basename "$d")
    [ "$name" = "User" ] && continue
    if printf '%s\n' "$want" | grep -qxF "$name"; then continue; fi
    run mkdir -p "$IP/.removed-$STAMP"
    run mv "$d" "$IP/.removed-$STAMP/"
    say "pruned $name (unpacked)"
    pruned=$((pruned + 1))
  done
  if [ "$pruned" -eq 0 ]; then
    say "nothing to prune — every installed package is accounted for"
  else
    say "$pruned pruned package(s) are in Installed Packages/.removed-$STAMP — delete when happy"
  fi
fi

echo
echo "  Done. Restart Sublime Text."
echo "  Package Control installs anything missing from the list on next launch."
echo
