# theme = "ferra"
# theme = "modus_vivendi"
# theme = "gruber-darker"
theme = "nanana"
# theme = "rose_pine_moon"
# theme = "material_palenight"
# theme = "yo_berry"
# theme = "catppuccin_mocha"
# theme = "catppuccin_latte"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
rulers = [120]
shell = ["zsh", "-c"]
bufferline = "always"
popup-border = "all"
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
completion-timeout = 50
color-modes = true
auto-pairs = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
# insert = "bar"
insert = "block"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable=false

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator", "file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# C-u = ["half_page_up", "align_view_center"]
# C-d = ["half_page_down", "align_view_center"]
X = ["extend_line_up"]
F1 = ["goto_previous_buffer"]
F2 = ["goto_next_buffer"]
C-k = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-j = [":new", ":insert-output tig", ":buffer-close!", ":redraw"]
# C-t = [":new", ":insert-output lf", ":buffer-close!", ":redraw"]
C-x = [":new", ":insert-output lf-pick",  "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw" ]
# space.o = ":sh gh repo view --web"
space.1 = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w95%% -h95%% -E yazi"
space.2 = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w95%% -h95%% -E lazygit"
space.3 = [":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w95%% -h95%% -E /Users/nikola/repos/ghostintherepo/makybara/makybara"]
space.4 = [":e from_clipboard"]
C-t = ["extend_to_line_bounds", ":pipe sh ~/.config/helix/exec.sh 2>&1"]
"ret" = "goto_word"
space.o = "file_picker_in_current_buffer_directory"

[keys.insert]
C-t = ["extend_to_line_bounds", ":pipe sh ~/.config/helix/exec.sh 2>&1", "normal_mode", "open_below"]
[keys.select]
C-t = [":pipe sh ~/.config/helix/exec.sh 2>&1"]

[keys.normal.g]
I = ":echo %sh{gh browse '%{buffer_name}:%{cursor_line}' -c}"
b = ":noop %sh{gh browse '%{buffer_name}:%{cursor_line}' -c}"
B = ":sh gh browse '%{buffer_name}:%{cursor_line}' -c"
# C-b = ":sh gh browse %{buffer_name}:%{cursor_line} -c=%sh{latest_pushed_commit}"
# B = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name} | sed -E 's/[0-9]+).*//' | sed 's/(//g'}"
# B = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name}}"

# [editor.whitespace]
# render = "all"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
# tab = "→"
# # newline =  "⏎"
# newline = "\\" # Tabs will look like "→···" (depending on tab width)
# # tabpad = "·" # Tabs will look like "→···" (depending on tab width)
# tabpad = "." # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"
#
