theme = "noctis"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
rulers = [81]
shell = ["zsh", "-c"]
bufferline = "always"
popup-border = "all"
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
completion-timeout = 50
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable=true

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator", "file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# C-u = ["half_page_up", "align_view_center"]
# C-d = ["half_page_down", "align_view_center"]
X = ["extend_line_up"]
F1 = ["goto_previous_buffer"]
F2 = ["goto_next_buffer"]
C-k = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
# C-t = [":new", ":insert-output lf", ":buffer-close!", ":redraw"]
C-x = [":new", ":insert-output lf-pick",  "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw" ]


# [editor.whitespace]
# render = "all"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
# tab = "→"
# # newline =  "⏎"
# newline = "\\" # Tabs will look like "→···" (depending on tab width)
# # tabpad = "·" # Tabs will look like "→···" (depending on tab width)
# tabpad = "." # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
