[[language]]
name = "python"
auto-format = true
[language.formatter]
command = "black"
args = [
"-", # stdin
"--quiet",
"--line-length=79",
]

[language-server.gopls.config]
buildFlags = ["-tags", "integration,e2e"]


[language-server.lua-language-server.config.Lua]
workspace = { library = ["${3rd}/love2d/library"] }
diagnostics = { globals = ["love"] }
completion = { enable = true, callSnippet = "Both" }
